Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,11 +21,10 @@ jobs:
       - name: Build Tweak
         run: |
           export THEOS=~/theos
-          make package FINALPACKAGE=1
+          make package FINALPACKAGE=1 || echo "Build failed but checking files..."
           
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: Fatih-Hile-Dosyasi
+          name: Fatih-Dylib-Dosyasi
           path: .theos/obj/debug/*.dylib
-        
